### PR TITLE
Don't send emails about closed projects; Also move some repeated logi…

### PR DESCRIPTION
**Pull request by mikeperalta1**
…c into its own method.

Hello again! I've been enjoying your plugin since our last exchange, but recently have noticed it sends emails about projects that have been closed.

This pull request is a patch that prevents the plugin from sending emails about closed projects. It also takes some repeated logic, and moves it into a dedicated method.

Hope you like it!

### CODE REVIEW

**Comment by creecros** [comment]
I don't have a server setup for testing, so, just gonna double check here, you've tested and its all good?

**Comment by mikeperalta1** [comment]
Yeah I'm running it on a private kanboard right now. No extensive testing, but I did try to trigger it in various ways, and it seems to work.

**Comment by creecros** [comment]
Well, if you break it, you fix it. ;)

**Comment by mikeperalta1** [comment]
lol deal

**Pull request merged**
